# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
  branches:
    include:
      - master
      - develop
      - release/*

trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
      - release/*
      - bugfix/*
      - hotfix/*

  paths:
    exclude:
      - spec/src/main/resources/apigeeConfig.yaml
      - spec/src/main/resources/azure-MAMCLI.yml
      - spec/src/main/resources/swagger.yml

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: importsbuildtemplate
      type: github
      name: Maersk-Global/imports-build-templates
      ref: main
      endpoint: ADOtoGitHub
    - repository: BDTemplateRepo
      type: github
      name: Maersk-Global/DOT-AzureDevops-CICD-templates
      ref: refs/heads/master # use master branch as default
      endpoint: ADOtoGitHub
    - repository: PolarisTemplateRepo
      type: github
      name: Maersk-Global/DOT-AzureDevops-CICD-templates
      ref: refs/heads/master # use master branch as default
      endpoint: ADOtoGitHub
    - repository: self

steps:
  - task: MavenAuthenticate@0
    displayName: Nexus MaerskDevNet Authentication
    inputs:
      mavenServiceConnections: 'NexusMaerskDevNetRW-OH-Modernization'
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'deploy'

  - template: imports_api_build_template.yml@importsbuildtemplate
    parameters:
      SKIP_SONAR: false
      NEXUS_MAERSK_DEV_NET_CONNECTION: NexusMaerskDevNetRW-OH-Modernization
      SONAR_QUBE_CONNECTION: ado_sonar_maerskdev_net_token-OH-Modernization